/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HelloHead.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

  const shineMaterial = new THREE.MeshPhongMaterial({
    color: "#6a88ff",
  });

export function HelloHead(props) {
  const { nodes, materials } = useGLTF('models/HelloHead.glb');
  // const screensRef = useRef();
  return (
    <group {...props} dispose={null}>
      
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.228}>
{/* 
        <EffectComposer>
                <SelectiveBloom
                  selection={screensRef}
                  intensity={1.5} // Strength of the bloom
                  luminanceThreshold={0.2} // Minimum luminance needed
                  luminanceSmoothing={0.9} // Smooth transition
                  blendFunction={BlendFunction.ADD} // How it blends
                />
              </EffectComposer> */}

        <mesh geometry={nodes.Mesh.geometry} material={materials['character:head']} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['character:face']} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials['character:headphones2']} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials['character:hair']} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials['character:headphones1']} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials['character:headphones3']} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials['character:bulb']} />
        <mesh geometry={nodes.Mesh_7.geometry} material={shineMaterial} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials.standardSurface1} />
      </group>
    </group>
  )
}

useGLTF.preload('models/HelloHead.glb')
